### ISSUE TITLE
RecycleView嵌套BannerView，奔溃

### ISSUE THREAD

**Issue by guoyanqiu** [ZhangHao555/BannerRecyclerView#7]
当父RecyclerView自己的notifyDataSetChanged的时候，子BannerView就会崩溃：
    kotlin.KotlinNullPointerException
        at com.shwatch.news.banner.BannerLayoutManager.scrollToLeft(BannerLayoutManager.kt:150)
        at com.shwatch.news.banner.BannerLayoutManager.offsetDx(BannerLayoutManager.kt:92)
        at com.shwatch.news.banner.BannerLayoutManager.scrollHorizontallyBy(BannerLayoutManager.kt:85)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4834)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)

**Comment by guoyanqiu** [comment]
解决了，setUp初始化BannerView的setup的时候调用一次就可以了，确切的说是其adapter调用一次就可以了

**Comment by guoyanqiu** [comment]
bannerView.setUp(bannerSetting,new Adapter(data));
改成
初始化BinnerView的时候
Adapter adapter = new Adapter(data);
 bannerView.setUp(bannerSetting,adapter);

然后在在设置设局的时候调用
adapter.setData(newData)

**Comment by guoyanqiu** [comment]
但是又遇到新问题了，就是在嵌套的RecyclerView，如果BannerView滑动到页面不可见，在划回来还是报错 getDecoratedRight报空指针
  private fun scrollToLeft(dx: Int, recycler: RecyclerView.Recycler): Int {
        var realScroll = dx
        while (true) {
            val rightView = getChildAt(childCount - 1)
            val decoratedRight = getDecoratedRight(rightView!!)

**Comment by guoyanqiu** [comment]
at com.shwatch.news.banner.BannerLayoutManager.scrollToLeft(BannerLayoutManager.kt:148)
        at com.shwatch.news.banner.BannerLayoutManager.offsetDx(BannerLayoutManager.kt:89)
        at com.shwatch.news.banner.BannerLayoutManager.scrollHorizontallyBy(BannerLayoutManager.kt:82)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4834)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)

**Comment by guoyanqiu** [comment]
根本原因BanerView的adapter不能调用notifyDataSetChanged

**Comment by ZhangHao555** [comment]
1.1.4已修复 adapter不能调用notifyDataSetChanged的bug
